### ISSUE TITLE
bleacherreport.com - impossible to go to exit fullscreen

### ISSUE THREAD

**Issue by karlcow** [bitmovin/bitmovin-player-ui#550] opened 2023-05-25 03:08 UTC
Steps to reproduce:

1. With Safari Technical Preview 170
2. Navigate to https://bleacherreport.com/
3. Enter fullscreen on a video
4. Attempt to exit fullscreen from onscreen controls (bottom right)

The code on the bleacherreport.com is not too bad, but then it becomes hard to decipher when inside bitmovin code because of the obfuscation. I'm trying to understand on which side is the issue. 

My hunch is not that much that it can't exit fullscreen, but that something it doesn't change state to signal it is in fullscreen. It's why the icon stays as is. 

```
e.on(e.exports.PlayerEvent.ViewModeChanged, (
    function() {
        e.getViewMode() === e.exports.ViewMode.Fullscreen 
            ? i.addClass(o.prefixCss(t.FULLSCREEN)) 
            : i.removeClass(o.prefixCss(t.FULLSCREEN))
        })),
e.getViewMode() === e.exports.ViewMode.Fullscreen && i.addClass(this.prefixCss(t.FULLSCREEN))
```

`e.getViewMode()` returns `inline`

When it goes to https://static-assets.bleacherreport.net/js/vendors~bitmovin-player-31cd1af0.js
It's… well… more difficult 😉

**Comment by dweinber** [comment] 2023-05-25 12:13
Hi @karlcow,

As you noticed, this isn't really a UI but a player issue, hence I'm closing this ticket in the UI repository.

Having said that, this is a known issue caused by a Safari bug around the events of the underlying fullscreen API. We have already implemented a mitigation for this problem in our player, which will be part of the upcoming release next Tuesday (8.119.0).

**Closed by dweinber** 2023-05-25 12:13 UTC

**Comment by karlcow** [comment] 2023-05-25 12:26
Thanks a lot @dweinber 
Do you know which Safari bug? on bugs.webkit.org?

**Comment by dweinber** [comment] 2023-05-25 13:10
Sorry, I got that slightly wrong. It's not a bug in Safari but a behavior change in the fullscreen-related events. I think from Safari it's expected behavior but this change messed with our state handling.

**Comment by karlcow** [comment] 2023-05-25 13:21
Thanks. This is 
https://bugs.webkit.org/show_bug.cgi?id=84798
and https://bugs.webkit.org/show_bug.cgi?id=229333

**Comment by nt1m** [comment] 2023-05-25 17:46
@dweinber Hi! Can I get more precision into why it messed up the state handling? Knowing what the fix you applied would be helpful too. I'm wondering if there are any more cases that started breaking with the new fullscreen API or if it's just isolated.

**Comment by dweinber** [comment] 2023-06-01 13:27
Hi @nt1m,

Essentially our player was listening to prefixed and unprefixed fullscreen change events to support the different browsers and implementation. So far, browsers had one or the other but starting with Safari 16.4, Safari emits both, `fullscreenchange` and `webkitfullscreenchange` events.

This caused the player to think it has left fullscreen mode already, even though it was still playing fullscreen. Hence, the button to de-toggle fullscreen didn't work. 

With the player version 8.119.0 and above, we now remember which event type has triggered the fullscreen mode, leading to interleaving events (like webkitfullscreenchange) not having an effect on the state in the player.

**Comment by nt1m** [comment] 2023-06-19 07:05
Thanks! that helped us provide a fix on our side as well: https://github.com/WebKit/WebKit/pull/14599

**Comment by dweinber** [comment] 2023-06-22 11:49
Nice, thanks for letting us know and for implementing the fix! 👍
