### ISSUE TITLE
I want to update the version of player 

### ISSUE THREAD

**Issue by devAliHaxan** [bitmovin/bitmovin-player-ui#541] opened 2023-03-20 08:51 UTC
currently i’m using 6.1.14 and i want to update it to latest 8.109.0.
These are the files previously i’m using but i din’t find the updated files of latest version.
i’m using these files by CDN.

-  bitmovinplayer-controls.min.css
-  bitmovinplayer-controls.min.js
-  bitmovinplayer-core.min.css
-  bitmovinplayer-core.min.js
-  bitmovinplayer-vr.min.js
-  bitmovinplayer-min.js
-  bitmovinplaer.swf

can anyone in community can help me how i can get the updated files.
thanks in advance

**Comment by dweinber** [comment] 2023-03-20 09:09
Hi @devAliHaxan,

As v6.1 was released in Feb 2017 (6 years ago!), with another major version in between v6 and the current v8, the upgrade won't be as straightforward as simply changing the files. Due to the age, I'm afraid we don't have a v6 to v7 migration guide anymore, only [v7 to v8](https://bitmovin.com/docs/player/tutorials/migration-guide-v7-to-v8) is still available.

I'd recommend starting at the Web Player's [Getting Started](https://bitmovin.com/docs/player/getting-started/web) docs, it contains relevant details like files to load and getting started with the new API. 
By the way, we strongly recommend using our [npm package](https://www.npmjs.com/package/bitmovin-player) to easily keep the player up to date.

As this is not a bug or feature suggestion for the Player UI, I'm closing this ticket. If you need further assistance with the upgrade, please post to the [Community](https://community.bitmovin.com/) or reach out to your Bitmovin representative.

**Closed by dweinber** 2023-03-20 09:09 UTC
