### ISSUE TITLE
Playing on the mobile devices requires double tap

### ISSUE THREAD

**Issue by ireneuszsawicki** [bitmovin/bitmovin-player-ui#10] opened 2017-04-06 14:21 UTC
Hi Guys,

As in the title, currently playing the video on the mobile device requires user to tap the player overlay twice (first to bring up UI, then start video playing). Is there any way to start video playback within single tap?

Best,
I.

**Comment by protyposis** [comment] 2017-04-06 17:18
Hi, that should already be fixed in the `release/v2.0.0-rc1` branch. Did you give it a try?

**Comment by ireneuszsawicki** [comment] 2017-04-06 19:55
Hi prototyposis,

I've just done a build from release/v2.0.0-rc1 branch, combined it with player v7.1.0-rc13 and pushed it to our server. It still requires double tap to play.

Additionally, I've commented out call to:
`this.configureMarkers(player, uimanager)`
in the SeekBar ts - it caused seeking bar to throw exceptions about calling `.metadata` on null.

**Comment by protyposis** [comment] 2017-04-07 06:28
I just tested it in Chrome/Firefox/Safari/Edge/IE on Android, iOS and Windows and cannot reproduce any of the problems. Single tap to play always worked. Which platform/browser are you experiencing that behavior on?

**Comment by ireneuszsawicki** [comment] 2017-04-07 06:40
We've encountered it on the Android & iPad. It's quite specific use case when ideally videos would autoplay, however on mobile devices it's blocked by default. If we have a video container on our website then user has to tap player once to set focus on the player and bring up controls, then he has to tap it again to start playing the video. Ideally we want a situation where user would tap player just once and video would start playing. I can pass you an example, but I'd prefer not to do it publicly.

**Comment by protyposis** [comment] 2017-04-07 06:47
An example would be helpful, you can mail it to mario.guggenberger@bitmovin.com

**Comment by ireneuszsawicki** [comment] 2017-04-10 10:12
Hey Protyposis,

We've found the issue. We're additionally calling .play() after launching the player and it has prevented iPad and Android devices from playing on single tap. It seems to work fine with 7.1 & v2.0.0 UI. Thanks for the previous fixes and checking.

**Closed** 2017-04-10 11:02 UTC
